# pylint: disable=line-too-long
FCCM = {
    (4096, 1): (
        "CCM 101",
        "Plasma Disabled",
        "Switch ON to Enable Plasma System possible phase loss, check mains fuses if enable is OK",
        "Plasma Enable Off ; Disable activated on TSC3000 or GCM 2010 or external SW disabled (CNC); CCM TB1-1&2 jumper missing; 40 circuit ribbon cable from Relay PCB to CCM disconnected or defective;",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=207",
        "-",
    ),
    (4096, 2): (
        "CCM 102",
        "Pilot Ignition Failure",
        "Torch Did not Ignite",
        "Pilot did not start within 15 seconds.  Torch consumable parts worn? Ensure correct process selected or manual setting including current control setting matches consumables; Plasma pressure too high; Defective Arc Starter; Defective Pilot PCB; defective Inverter section 1A.  Ribbon cables reversed on INV1 sections 1A and 1B.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=209",
        "https://youtu.be/1UiqeHi0xlg",
    ),
    (4096, 3): (
        "CCM 103",
        "Lost Pilot",
        "Pilot occured but could not be maintained",
        "Pilot went out while Start active.  Torch consumable parts worn? Ensure cut process or current control setting setting matches consumables; Plasma pressure too high;",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=213",
        "-",
    ),
    (4096, 4): (
        "CCM 104",
        "Transfer Lost",
        "Transfer occured but could not be maintained",
        "Arc was transferred to work then went out while Start still active.  Arc lost contact with work (run OFF edge, over hole, etc.); Standoff too high; Ensure cut process or manual settings (current control, gas pressures) matches consumables;",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=213",
        "-",
    ),
    (4096, 5): (
        "CCM 105",
        "Not used",
        "Torch moved off the cutting surface causing unexpected end of cut.,",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4096, 6): (
        "CCM 106",
        "Pilot Timeout, no Transfer",
        "-",
        "Must transfer from Pilot to Cutting Arc in 0.085 seconds (SW8-1 OFF) or 3 sec.  (SW8-1 ON).  Standoff too high or void in work under torch; Wrong cut process selected or wrong manual settings (current control set too low or wrong gas pressure).",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=214",
        "https://youtu.be/J90Psy5Q4cA",
    ),
    (4096, 7): (
        "CCM 107",
        "Tip Saver Fault",
        "-",
        "Tip remained in contact with work in excess of 15 seconds.  ( Pak200i).",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=214",
        "-",
    ),
    (4096, 8): (
        "CCM 108",
        "Tip to Electrode voltage fault.",
        "Torch volts too low for pilot.,",
        "Tip voltage too close to electrode voltage; Torch consumable parts worn out; Wrong consumables installed causing tip to electrode short; Wrong process selected or wrong manual setting of plasma gas or cutting current.; Leak in Plasma hose to torch; Defective Pilot PCB; Shorted torch body .",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=214",
        "https://youtu.be/RuRgSMi2Zik",
    ),
    (4096, 9): (
        "CCM 109",
        "Part process not configured.",
        "DFC 3000 only - Select process and send to DFC.,",
        "Applies only to DFC 3000 Auto Gas Control.  Select and load a cutting process.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=215",
        "-",
    ),
    (4096, 10): (
        "CCM 110",
        "Device Locked",
        "Process loading, wait until finished.,",
        "DFC 3000: Process loading; wait until finished",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=215",
        "-",
    ),
    (4097, 1): (
        "CCM 201",
        "Missing AC Phase",
        "-",
        "Blown wall fuse, Blown unit fuse F1 or F2 or rear panel, Bad power cable connection; Defective System Bias PCB.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=216",
        "-",
    ),
    (4097, 2): (
        "CCM 202",
        "Not used",
        "-",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4097, 3): (
        "CCM 203",
        "Not used",
        "-",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4097, 4): (
        "CCM 204",
        "Not used",
        "-",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4097, 5): (
        "CCM 205",
        "DC Output Low",
        "-",
        "Less than 60 VDC; Negative lead short to work or ground; Defective inverter (output shorted); CCM voltage sense (J24) disconnected or wire broken; Defective CCM ",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=217",
        "-",
    ),
    (4097, 6): (
        "CCM 206",
        "Not used",
        "-",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4097, 7): (
        "CCM 207",
        "Unexpected current in work lead",
        "-",
        "Current above 8A in work lead prior to pilot ignition or transfer.  Negative lead short to ground or arcstarter chassis; Defective HCT1 work lead current sensor; Defective Relay PCB.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=218",
        "-",
    ),
    (4097, 8): (
        "CCM 208",
        "Unexpected current in pilot circuit",
        "-",
        "Current above 6A in pilot circuit prior to ignition.  Wrong or mismatched consumables causing tip - electrode short; Pilot lead shorted to negative in torch tube; Defective Relay PCB; Defective Pilot PCB; Possible shorted torch.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=219",
        "-",
    ),
    (4097, 9): (
        "CCM 209",
        "Not used",
        "-",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4097, 10): (
        "CCM 210",
        "Work Current Too High",
        "-",
        "Work lead current detected greater than 16% above process setting.  Possible defective HCT1 Work lead current sensor or Relay PCB; Defective CCM ",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 11): (
        "CCM 211",
        "Work Current Too Low",
        "-",
        "Work current detected more than 16% below process setting.  Possible defective HCT1 Work lead current sensor or Relay PCB; Possible defective pilot PCB (shorted IGBT);",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 12): (
        "CCM 212",
        "Inverter 1A Output Current Low",
        "-",
        "Plasma work current low during cutting and attributed to Inverter Module 1 Section A output low; Inverter output disconnected; Possible defective ribbon cable; If problem persists replace Inverter Module 1",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 13): (
        "CCM 213",
        "Inverter 1B Output Current Low",
        "-",
        "Plasma work current low during cutting and attributed to Inverter Module 1 Section B output low; Inverter output disconnected; Possible defective ribbon cable; If problem persists replace Inverter Module 1",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 14): (
        "CCM 214",
        "Inverter 2A Output Current Low",
        "-",
        "Plasma work current low during cutting and attributed to Inverter Module 2 Section A output low; Inverter output disconnected; Possible defective ribbon cable; If problem persists replace Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 15): (
        "CCM 215",
        "Inverter 2B Output Current Low",
        "-",
        "Plasma work current low during cutting and attributed to Inverter Module 2 Section B output low; Inverter output disconnected; Possible defective ribbon cable; If problem persists replace Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 16): (
        "CCM 216",
        "Inverter 3A Output Current Low",
        "-",
        "Plasma work current low during cutting and attributed to Inverter Module 3 Section A output low; Inverter output disconnected; Possible defective ribbon cable; If problem persists replace Inverter Module 3",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 17): (
        "CCM 217",
        "Inverter 3B Output Current Low",
        "-",
        "Plasma work current low during cutting and attributed to Inverter Module 3 Section B output low; Inverter output disconnected; Possible defective ribbon cable; If problem persists replace Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 18): (
        "CCM 218",
        "Inverter 1A Output Current High",
        "-",
        "Plasma work current high during cutting and attributed to Inverter Module 1 Section A output high; If problem persists replace Inverter Module 1",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 19): (
        "CCM 219",
        "Inverter 1B Output Current High",
        "-",
        "Plasma work current high during cutting and attributed to Inverter Module 1 Section B output high; If problem persists replace Inverter Module 1",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 20): (
        "CCM 220",
        "Inverter 2A Output Current High",
        "-",
        "Plasma work current high during cutting and attributed to Inverter Module 2 Section A output high; If problem persists replace Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 21): (
        "CCM 221",
        "Inverter 2B Output Current High",
        "-",
        "Plasma work current high during cutting and attributed to Inverter Module 2 Section B output high; If problem persists replace Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 22): (
        "CCM 222",
        "Inverter 3A Output Current High",
        "-",
        "Plasma work current high during cutting and attributed to Inverter Module 3 Section A output high; If problem persists replace Inverter Module 3",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 23): (
        "CCM 223",
        "Inverter 3B Output Current High",
        "-",
        "Plasma work current high during cutting and attributed to Inverter Module 3 Section B output high; If problem persists replace Inverter Module 3",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=220",
        "-",
    ),
    (4097, 24): (
        "CCM 224",
        "Inverter 1 Not Found",
        "-",
        "Inverter Module 1 Section A required for Piloting; Bad ribbon cable connection to CCM J31 to Inverter Module 1 Section A.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 25): (
        "CCM 225",
        "Inverter 1A Incompatible Revision",
        "-",
        "Unsupported Inverter Revision; Ribbon cable CCM J31 to Inverter Module 1 Section A damaged; CCM code version incompatible with Inverter revision or model",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 26): (
        "CCM 226",
        "Inverter 1B Incompatible Revision",
        "-",
        "Unsupported Inverter Revision; Ribbon cable CCM J32 to Inverter Module 1 Section B damaged ; CCM code version incompatible with Inverter revision or model",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 27): (
        "CCM 227",
        "Inverter 2A Incompatible Revision",
        "-",
        "Unsupported Inverter Revision; Ribbon cable CCM J33 to Inverter Module 2 Section A damaged; CCM code version incompatible with Inverter revision or model",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 28): (
        "CCM 228",
        "Inverter 2B Incompatible Revision",
        "-",
        "Unsupported Inverter Revision; Ribbon cable CCM J34 to Inverter Module 2 Section B damaged; CCM code version incompatible with Inverter revision or model",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 29): (
        "CCM 229",
        "Inverter 3A Incompatible Revision",
        "-",
        "Unsupported Inverter Revision; Ribbon cable CCM J35 to Inverter Module 3 Section A damaged; CCM code version incompatible with Inverter revision or model",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 30): (
        "CCM 230",
        "Inverter 3B Incompatible Revision",
        "-",
        "Unsupported Inverter Revision; Ribbon cable CCM J36 to Inverter Module 3 Section B damaged; CCM code version incompatible with Inverter revision or model",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=221",
        "-",
    ),
    (4097, 31): (
        "CCM 231",
        "Inverter 1A VAC Mismatch",
        "-",
        "Inverter AC Voltage rating incompatible with Power Supply voltage rating; Bad ribbon cable connection CCM J31 to Inverter Module 1 Section A; Wrong voltage Inverter Module 1 installed; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=222",
        "-",
    ),
    (4097, 32): (
        "CCM 232",
        "Inverter 1B VAC Mismatch",
        "-",
        "Inverter AC Voltage rating incompatible with Power Supply voltage rating; Bad ribbon cable connection CCM J32 to Inverter Module 1 Section B; Wrong voltage Inverter Module 1 installed; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=222",
        "-",
    ),
    (4097, 33): (
        "CCM 233",
        "Inverter 2A VAC Mismatch",
        "-",
        "Inverter AC Voltage rating incompatible with Power Supply voltage rating; Bad ribbon cable connection CCM J33 to Inverter Module 2 Section A; Wrong voltage Inverter Module 2 installed; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=222",
        "-",
    ),
    (4097, 34): (
        "CCM 234",
        "Inverter 2B VAC Mismatch",
        "-",
        "Inverter AC Voltage rating incompatible with Power Supply voltage rating; Bad ribbon cable connection CCM J34 to Inverter Module 2 Section B; Wrong voltage Inverter Module 2 installed; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=222",
        "-",
    ),
    (4097, 35): (
        "CCM 235",
        "Inverter 3A VAC Mismatch",
        "-",
        "Inverter AC Voltage rating incompatible with Power Supply voltage rating; Bad ribbon cable connection CCM J35 to Inverter Module 3 Section A; Wrong voltage Inverter Module 3 installed; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=222",
        "-",
    ),
    (4097, 36): (
        "CCM 236",
        "Inverter 3B VAC Mismatch",
        "-",
        "Inverter AC Voltage rating incompatible with Power Supply voltage rating; Bad ribbon cable connection CCM J36 to Inverter Module 3 Section B; Wrong voltage Inverter Module 3 installed; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=222",
        "-",
    ),
    (4097, 37): (
        "CCM 237",
        "Too Few Inverters Found",
        "-",
        "Two or more Inverter Sections required to operate; Ribbon cable from CCM to Inverter Section damaged or disconnected;",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=223",
        "-",
    ),
    (4097, 38): (
        "CCM 238",
        "BIAS VAC Invalid",
        "-",
        "Invalid AC Voltage Selection; Damaged or loose connection at J61 of System Bias Supply; Defective System Bias PCB",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=223",
        "-",
    ),
    (4097, 39): (
        "CCM 239",
        "AC Voltage High",
        "-",
        "System Bias PCB detected AC Voltage is higher than Power Supply rated Voltage; System Bias Supply J61 Voltage Selection connection damaged or disconnected; Defective System Bias PCB; Defective CCM ",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=224",
        "-",
    ),
    (4097, 40): (
        "CCM 240",
        "AC Voltage Low",
        "-",
        "System Bias PCB detected AC Voltage is lower than Power Supply rated Voltage; System Bias Supply J61 Voltage Selection connection damaged or disconnected; Defective System Bias PCB; Defective CCM ",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=224",
        "-",
    ),
    (4097, 41): (
        "CCM 241",
        "Inverter 1A Input Voltage Error",
        "-",
        "Inverter Input Voltage fault; voltage out of range or missing phase at AC Input of Inverter Module 1 Section A; Poor AC Power Quality; Defective W1 contactor; Loose or open connection between input terminals and W1 contactor or contactor and input of Inverter Section; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=225",
        "-",
    ),
    (4097, 42): (
        "CCM 242",
        "Inverter 1B Input Voltage Error",
        "-",
        "Inverter Input Voltage fault; voltage out of range or missing phase at AC Input of Inverter Module 1 Section B; Poor AC Power Quality; Defective W1 contactor; Loose or open connection between input terminals and W1 contactor or contactor and input of Inverter Section; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=225",
        "-",
    ),
    (4097, 43): (
        "CCM 243",
        "Inverter 2A Input Voltage Error",
        "-",
        "Inverter Input Voltage fault; voltage out of range or missing phase at AC Input of Inverter Module 2 Section A; Poor AC Power Quality; Defective W1 contactor; Loose or open connection between input terminals and W1 contactor or contactor and input of Inverter Section; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=225",
        "-",
    ),
    (4097, 44): (
        "CCM 244",
        "Inverter 2B Input Voltage Error",
        "-",
        "Inverter Input Voltage fault; voltage out of range or missing phase at AC Input of Inverter Module 2 Section B; Poor AC Power Quality; Defective W2 contactor; Loose or open connection between input terminals and W2 contactor or contactor and input of Inverter Section; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=225",
        "-",
    ),
    (4097, 45): (
        "CCM 245",
        "Inverter 3A Input Voltage Error",
        "-",
        "Inverter Input Voltage fault; voltage out of range or missing phase at AC Input of Inverter Module 3 Section A; Poor AC Power Quality; Defective W2 contactor; Loose or open connection between input terminals and W2 contactor or contactor and input of Inverter Section; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=225",
        "-",
    ),
    (4097, 46): (
        "CCM 246",
        "Inverter 3B Input Voltage Error",
        "-",
        "Inverter Input Voltage fault; voltage out of range or missing phase at AC Input of Inverter Module 3 Section B; Poor AC Power Quality; Defective W2 contactor; Loose or open connection between input terminals and W2 contactor or contactor and input of Inverter Section; Defective Inverter module",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=225",
        "-",
    ),
    (4097, 47): (
        "CCM 247",
        "Inverter 1A Circuit Fault",
        "-",
        "Inverter Module 1 Section A detected a circuit fault; Damaged Inverter Module 1",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 48): (
        "CCM 248",
        "Inverter 1B Circuit Fault",
        "-",
        "Inverter Module 1 Section B detected a circuit fault; Damaged Inverter Module 1",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 49): (
        "CCM 249",
        "Inverter 2A Circuit Fault",
        "-",
        "Inverter Module 2 Section A detected a circuit fault; Damaged Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 50): (
        "CCM 250",
        "Inverter 2B Circuit Fault",
        "-",
        "Inverter Module 2 Section B detected a circuit fault; Damaged Inverter Module 2",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 51): (
        "CCM 251",
        "Inverter 3A Circuit Fault",
        "-",
        "Inverter Module 3 Section A detected a circuit fault; Damaged Inverter Module 3",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 52): (
        "CCM 252",
        "Inverter 3B Circuit Fault",
        "-",
        "Inverter Module 3 Section B detected a circuit fault; Damaged Inverter Module 3",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 53): (
        "CCM 253",
        "Inverter 1A Over Temp",
        "-",
        "Inverter Module 1 Section A is over temperature; Operating with side panels removed, Check for restricted air flow, clogged radiator; Defective fan; If problem persists replace inverter module.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 54): (
        "CCM 254",
        "Inverter 1B Over Temp",
        "-",
        "Inverter Module 1 Section B is over temperature; Operating with side panels removed, Check for restricted air flow, clogged radiator; Defective fan; If problem persists replace inverter module.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 55): (
        "CCM 255",
        "Inverter 2A Over Temp",
        "-",
        "Inverter Module 2 Section A is over temperature; Operating with side panels removed, Check for restricted air flow, clogged radiator; Defective fan; If problem persists replace inverter module.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 56): (
        "CCM 256",
        "Inverter 2B Over Temp",
        "-",
        "Inverter Module 2 Section B is over temperature; Operating with side panels removed, Check for restricted air flow, clogged radiator; Defective fan; If problem persists replace inverter module.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 57): (
        "CCM 257",
        "Inverter 3A Over Temp",
        "-",
        "Inverter Module 3 Section A is over temperature; Operating with side panels removed, Check for restricted air flow, clogged radiator; Defective fan; If problem persists replace inverter module.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 58): (
        "CCM 258",
        "Inverter 3B Over Temp",
        "-",
        "Inverter Module 3 Section B is over temperature; Operating with side panels removed, Check for restricted air flow, clogged radiator; Defective fan; If problem persists replace inverter module.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=226",
        "-",
    ),
    (4097, 59): (
        "CCM 259",
        "Inverter 1A Over Temp Ambient",
        "-",
        "Inverter circuitry is over temperature likely cause is ambient greater than 40 deg C; Reduce power supply cutting Duty Cycle; Reduce ambient air temperature; Add auxiliary cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 60): (
        "CCM 260",
        "Inverter 1B Over Temp Ambient",
        "-",
        "Inverter circuitry is over temperature likely cause is ambient greater than 40 deg C; Reduce power supply cutting Duty Cycle; Reduce ambient air temperature; Add auxiliary cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 61): (
        "CCM 261",
        "Inverter 2A Over Temp Ambient",
        "-",
        "Inverter circuitry is over temperature likely cause is ambient greater than 40 deg C; Reduce power supply cutting Duty Cycle; Reduce ambient air temperature; Add auxiliary cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 62): (
        "CCM 262",
        "Inverter 2B Over Temp Ambient",
        "-",
        "Inverter circuitry is over temperature likely cause is ambient greater than 40 deg C; Reduce power supply cutting Duty Cycle; Reduce ambient air temperature; Add auxiliary cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 63): (
        "CCM 263",
        "Inverter 3A Over Temp Ambient",
        "-",
        "Inverter circuitry is over temperature likely cause is ambient greater than 40 deg C; Reduce power supply cutting Duty Cycle; Reduce ambient air temperature; Add auxiliary cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 64): (
        "CCM 264",
        "Inverter 3B Over Temp Ambient",
        "-",
        "Inverter circuitry is over temperature likely cause is ambient greater than 40 deg C; Reduce power supply cutting Duty Cycle; Reduce ambient air temperature; Add auxiliary cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 65): (
        "CCM 265",
        "Inverter 1A No Input Power",
        "-",
        "Inverter section may have no input power.  Contactor W1 not closed; Defective contactor or CB4 tripped; Inverter section input not connected; Defective Inverter.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 66): (
        "CCM 266",
        "Inverter 1B No Input Power",
        "-",
        "Inverter section may have no input power.  Contactor W1 not closed; Defective contactor or CB4 tripped; Inverter section input not connected; Defective Inverter.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 67): (
        "CCM 267",
        "Inverter 2A No Input Power",
        "-",
        "Inverter section may have no input power.  Contactor W1 not closed; Defective contactor or CB4 tripped; Inverter section input not connected; Defective Inverter.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 68): (
        "CCM 268",
        "Inverter 2B No Input Power",
        "-",
        "Inverter section may have no input power.  Contactor W2 not closed; Defective contactor or CB4 tripped; Inverter section input not connected; Defective Inverter.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 69): (
        "CCM 269",
        "Inverter 3A No Input Power",
        "-",
        "Inverter section may have no input power.  Contactor W2 not closed; Defective contactor or CB4 tripped; Inverter section input not connected; Defective Inverter.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 70): (
        "CCM 270",
        "Inverter 3B No Input Power",
        "-",
        "Inverter section may have no input power.  Contactor W2 not closed; Defective contactor or CB4 tripped; Inverter section input not connected; Defective Inverter.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=227",
        "-",
    ),
    (4097, 71): (
        "CCM 271",
        "Inverter ID reading fault",
        "-",
        "CCM found ID values inconsistent during reading.  CCM to an Inverter section ribbon damaged or disconnected; Improper ribbon cable routing.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=228",
        "-",
    ),
    (4098, 1): (
        "CCM 301",
        "Gas control communication fault",
        "-",
        "Problem with fiber optic cable to GCM 2010 or DMC or DPC; Dirt on fiber ends or in connectors; blow out with clean dry air.  Fiber not locked into connector; Sharp bends in fiber cable; Fiber defective; GCM 2010 circuit board defect; DMC or DPC power supply defective; DMC or DPC circuit board defect",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=229",
        "-",
    ),
    (4098, 2): (
        "CCM 302",
        "Gas Control reply fault",
        "-",
        "Problem with fiber optic cable to GCM 2010 or DMC or DPC; Dirt on fiber ends or in connectors; blow out with clean dry air.  Fiber not locked into connector; Sharp bends in fiber cable; Fiber defective; GCM 2010 circuit board defect; DMC or DPC power supply defective; DMC or DPC circuit board defect",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=229",
        "-",
    ),
    (4098, 3): (
        "CCM 303",
        "Gas Supply Pressure out of range.",
        "Supply pressure is out of range",
        "GCM 2010 inlet plasma or shield pressure low or defective pressure sensors PS3 & PS4; Defective GCM 2010 PCB; For DFC 3000 see DPC for pressure faults.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=229",
        "-",
    ),
    (4098, 4): (
        "CCM 304",
        "Gas Control Purging",
        "-",
        "Normal following power up or returning from Plasma Disable.  Wait for purge to finish.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=229",
        "-",
    ),
    (4098, 5): (
        "CCM 305",
        "Gas Control protocol error",
        "-",
        "Verify Firmware revision for compatibility with GCM 2010 or DMC and DPC",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=230",
        "-",
    ),
    (4098, 6): (
        "CCM 306",
        "Not used",
        "-",
        "Reserved for other future use.",
        "-",
        "-",
        "-",
    ),
    (4098, 7): (
        "CCM 307",
        "Gas Control sequencing error",
        "-",
        "Verify Firmware revision for compatibility with GCM 2010 or DMC and DPC",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=230",
        "-",
    ),
    (4098, 8): (
        "CCM 308",
        "Gas Control Type Mismatch",
        "-",
        "Wrong CCM (Auto-Cut or Pak 200 type?) for UC; Install correct CCM ",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=230",
        "-",
    ),
    (4098, 9): (
        "CCM 309",
        "Gas Control command fault",
        "-",
        "Verify Firmware revision for compatibility with GCM 2010 or DMC and DPC; Electromagnetic interference with Arc Starter; inspect grounding; bonding; and isolation",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=230",
        "-",
    ),
    (4098, 10): (
        "CCM 310",
        "DPC fault",
        "Check DPC status indicator for specific problem",
        "Check DPC status indicator for specific problem",
        "-",
        "-",
        "-",
    ),
    (4098, 11): (
        "CCM 311",
        "DPC valve control fault",
        "Check DPC status indicator for specific problem",
        "Check DPC status indicator for specific problem",
        "-",
        "-",
        "-",
    ),
    (4098, 12): (
        "CCM 312",
        "DMC fault",
        "Check DMC status indicator for specific problem",
        "Check DMC status indicator for specific problem",
        "-",
        "-",
        "-",
    ),
    (4098, 13): (
        "CCM 313",
        "Gas Controller not configured.",
        "DMC and/or DPC not configured for a process or locked. See DMC and DPC status",
        "DMC or DPC not configured for a process or locked; See DMC and DPC status",
        "-",
        "-",
        "-",
    ),
    (4099, 1): (
        "CCM 401",
        "Coolant Level low",
        "-",
        "Check coolant level, add as needed.  Defective or disconnected level sensor.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=231",
        "-",
    ),
    (4099, 2): (
        "CCM 402",
        "Low coolant flow",
        "-",
        "Coolant flow as measured by flow switch FS1 is less than 0.7 gpm (0.25 for Pak200i); Clogged filter; Restriction in torch lead or head; Wrong style consumables; Bad O-ring on the torch check valve; broken or defective torch coolant tube/check valve; Defective pump or bypass valve.  402 code along with 104 code is probably a low flow problem.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=231",
        "-",
    ),
    (4099, 3): (
        "CCM 403",
        "Coolant overheated",
        "-",
        "Coolant supply temperature exceeded 75 degrees Celsius (167F).  Operating with side panel loose or removed; Air flow blocked at air inlet or exit of power supply; Coolant fan failed; radiator fins clogged with dirt.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=232",
        "-",
    ),
    (4099, 4): (
        "CCM 404",
        "Coolant System not ready.",
        "-",
        "Proper coolant flow of 0.7 gpm as measured by flow switch FS1 was not obtained during up to 4 minutes of Priming.  New installation can require additional Priming cycle(s) to fill hoses with coolant; cycle power to restart Priming; Coolant hoses or torch hoses reversed; Clogged coolant filter; Restriction in torch lead or head; Wrong style consumables; broken or defective torch coolant tube/check valve; Defective or disconnected FS1 flow SW; Defective pump or bypass valve.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=233",
        "-",
    ),
    (4099, 5): (
        "CCM 405",
        "Low Coolant Level Warning",
        "-",
        "Low coolant level during cut, does not stop cut.  Add coolant as required.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=236",
        "-",
    ),
    (4099, 6): (
        "CCM 406",
        "Not Used",
        "-",
        "Reserved for legacy product",
        "-",
        "-",
        "-",
    ),
    (4099, 7): (
        "CCM 407",
        "Coolant overheated, high ambient.",
        "-",
        "Coolant supply temperature exceeded 75 degrees Celsius (167F) likely cause ambient greater than 40 degrees Celsius (104F); Reduce cutting duty cycle; Reduce ambient temperature; Add separate coolant cooler.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=236",
        "-",
    ),
    (4100, 1): (
        "CCM 501",
        "CANBUS Acknowledge Fault",
        "-",
        "CCM to DMC Fiber-optic Control cable not connected, not properly connected or cable defective.  DMC power supply or Control PCB defective.  Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=236",
        "-",
    ),
    (4100, 2): (
        "CCM 502",
        "CANBUS Off",
        "-",
        "Dirt on fiber ends or in connectors; blow out with clean dry air; Fiber not locked into connector; Sharp bends in fiber; Fiber defective",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4100, 3): (
        "CCM 503",
        "CANBUS Errors Warning",
        "-",
        "Dirt on fiber ends or in connectors; blow out with clean dry air; Fiber not locked into connector; Sharp bends in fiber; Fiber defective;",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4100, 4): (
        "CCM 504",
        "Reserved",
        "-",
        "No information available; Contact customer service",
        "-",
        "-",
        "-",
    ),
    (4101, 1): (
        "CCM 601",
        "Analog Voltage Error",
        "-",
        "Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 2): (
        "CCM 602",
        "ADC or DAC error",
        "Replace CCM",
        "Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 3): (
        "CCM 603",
        "Reserved",
        "-",
        "No information available; Contact customer service",
        "-",
        "-",
        "-",
    ),
    (4101, 4): (
        "CCM 604",
        "Data Memory error",
        "Replace CCM",
        "Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 5): (
        "CCM 605",
        "Program memory fault",
        "Replace CCM",
        "Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 6): (
        "CCM 606",
        "+5V Logic supply low",
        "Replace CCM",
        "Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 7): (
        "CCM 607",
        "Processor over temperature",
        "Replace CCM",
        "Reduce ambient temperature; Defective CCM; replace",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 8): (
        "CCM 608",
        "5V supply for RS 485/422 communication low.",
        "Replace CCM",
        "Defective CCM  replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 9): (
        "CCM 609",
        "Firmware Update Device Error",
        "Replace CCM",
        "Defective CCM; replace",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 10): (
        "CCM 610",
        "Firmware Update Protocol Error",
        "Replace CCM",
        "Defective CCM; replace",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 11): (
        "CCM 611",
        "USB Controller Fault",
        "Replace CCM",
        "Defective CCM; replace",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 12): (
        "CCM 612",
        "USB Power Fault",
        "Replace CCM",
        "Faulty USB device plugged into USB port, remove; Defective CCM",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 13): (
        "CCM 613",
        "USB Log Creation Fault",
        "Replace CCM",
        "Unable to create Log file on USB Flash drive last firmware update attempt; Use different USB Flash Drive or Reformat",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=238",
        "-",
    ),
    (4101, 14): (
        "CCM 614",
        "No USF File",
        "-",
        "File VTCCMFW.USF missing from Flash Drive; Add proper files to Flash Drive for Firmware Update; Use different USB Flash Drive or Reformat",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=239",
        "-",
    ),
    (4101, 15): (
        "CCM 615",
        "No CCM Update File",
        "-",
        "CCM Firmware file specified in VTCCMFW.USF not found ; Add proper files to Flash Drive for Firmware updating",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=239",
        "-",
    ),
    (4101, 16): (
        "CCM 616",
        "DPC Update Fault",
        "-",
        "Fault occurred attempting to update DPC firmware; Add proper files to USB Flash drive for Firmware updating; Refer to CCM_LOG.TXT on Flash Drive for details",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=239",
        "-",
    ),
    (4101, 17): (
        "CCM 617",
        "DMC Update Fault",
        "-",
        "Fault occurred attempting to update DMC firmware; Add proper files to USB Flash drive for Firmware updating; Refer to CCM_LOG.TXT on Flash Drive for details",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=239",
        "-",
    ),
    (4101, 18): (
        "CCM 618",
        "ADC Calibration Fault",
        "-",
        "Error too large calibrating ADC; Fault persists defective CCM;",
        "-",
        "-",
        "-",
    ),
    (4101, 19): (
        "CCM 619",
        "Flow Switch Fault",
        "-",
        "Flow switch reporting coolant flow when pump OFF;",
        "-",
        "-",
        "-",
    ),
    (4101, 20): (
        "CCM 620",
        "Non Volatile Memory Error",
        "-",
        "Non Volatile Memory Storage Corrupted and Erased; Fault persists defective CCM ",
        "-",
        "-",
        "-",
    ),
    (4101, 21): (
        "CCM 621",
        "USB Format Fault",
        "-",
        "A USB flash drive was detected but could not be read by CCM   Backup any files currently on flash drive, reformat the USB flash drive to a FAT or FAT32 file system, replace only the CCM update files and try again.  Use different USB flash drive formatted with FAT or FAT32 file system.",
        "-",
        "-",
        "-",
    ),
    (4101, 22): (
        "CCM 622",
        "CCM Code Execution Fault",
        "Replace Firmware",
        "Possible EMI noise problem or code fault.  Check for proper grounding and bonding of equipment and routing of torch leads and cables to reduce Electromagnetic Emission Interference onto CCM module.  If problem persists, verify CCM code version is the latest supported revision.  Replace CCM module.",
        "-",
        "-",
        "-",
    ),
    (4102, 1): (
        "CCM 701",
        "Isolation Contactor Fault",
        "-",
        "1Torch isolation contactor W5 appears closed when expected to be open.  Contacts may fused or, W5 could be energized, 24 VAC on it's coil, when it should not be due to faulty Relay PCB.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=242",
        "-",
    ),
    (4102, 2): (
        "CCM 702",
        "Contact Start consumable fault",
        "-",
        "Prior to 1 torch preflow there should be continuity from the electrode, through the start cartridge, to the tip.  Failure may be due to worn or missing consumable or Start Cartridge.  Inspect, clean or replace.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=243",
        "-",
    ),
    (4102, 3): (
        "CCM 703",
        "Contact Start detection circuit fault",
        "-",
        "In the 1Torch module K201 should energize when W5 does.  Either it failed to energize or the pressure switch PS2 is failed closed.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=243",
        "-",
    ),
    (4102, 4): (
        "CCM 704",
        "Contact Start pressure fault",
        "-",
        "Pressure switch PS2 detects less than 35 PSI.  Normal pressure is 75-85 PSI.  No air connected to the 1Torch module inlet or it's too low pressure; if using optional single stage filter the element may need cleaning or replacement, refer to maintenance section. ;1Torch pressure regulator set too low; 1 torch module solenoid SOL4 has failed; Relay PCB does not apply 24 VAC to SOL4.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=244",
        "-",
    ),
    (4102, 5): (
        "CCM 705",
        "Contact Start Cartridge fault",
        "-",
        "Air pressure should separate the Start Cartridge from the tip to initiate pilot.  Failure may be stuck or damaged cartridge or consumables.  Clean or replace.  Or no DC output from inverters, front panel DC LED does not come on.",
        "https://www.thermal-dynamics.com/thermal-dynamics/shared/content/RequestLiterature/EN-UK/UltraCutXTHighPrecision/upload/0-5578.pdf",
        "page=244",
        "-",
    ),
    (4103, 1): (
        "CCM 801",
        "Shown on PS2 only, indicating fault in PS1 unit",
        "See PS1 for cause of error",
        "Fault in Primary power supply (PS1), Read PS1 fault display, refer to all group faults for corrective action, cycle both PS1 and PS2 power when fault is corrected.",
        "-",
        "-",
        "-",
    ),
    (4103, 2): (
        "CCM 802",
        "Shown on PS1 only, indicating fault in PS2 unit",
        "See PS2 for cause of error",
        "Fault in Secondary power supply (PS2), Read PS2 fault display, refer to all group faults for corrective action, cycle both PS1 and PS2 power when fault is corrected.",
        "-",
        "-",
        "-",
    ),
    (4103, 3): (
        "CCM 803",
        "Shown on PS1 only, indicating fault with communication between PS1 and PS2 unit",
        "Communication problem between PS1 and PS2",
        "Turn PS2 power on, Check fiber optic cable connection between PS1 and PS2, Replace fiber optic cable, determine if CCM is defective by swapping in a known good CCM module",
        "-",
        "-",
        "-",
    ),
}
FDMC = {
    (8192, 1): (
        "DMC 1-1",
        "Plasma Disabled",
        "Enable Plasma",
        "Enable Plasma;  Defective DMC Power Supply",
        "-",
        "-",
        "-",
    ),
    (8192, 2): (
        "DMC 1-2",
        "VDC 24 fault",
        "Check /replace DMC power supply or Replace DMC control PCB",
        "Check / replace DMC Power Supply Fuse F2; Replace DMC power supply PCB; Replace DMC control PCB",
        "-",
        "-",
        "-",
    ),
    (8192, 3): (
        "DMC 1-3",
        "VDC 5 fault",
        "Check /replace DMC power supply or Replace DMC control PCB",
        "Check /replace DMC power supply or Replace DMC control PCB",
        "-",
        "-",
        "-",
    ),
    (8192, 4): (
        "DMC 1-4",
        "No process selected",
        "Select and send process from TSC 3000 or CNC",
        "Select and send process from TSC 3000 or CNC",
        "-",
        "-",
        "-",
    ),
    (8192, 5): (
        "DMC 1-5",
        "DMC is locked",
        "Process loading, wait until finished",
        "Process loading  wait until finished",
        "-",
        "-",
        "-",
    ),
    (8192, 6): (
        "DMC 1-6",
        "Not Purged",
        "an attempt was made to activate solenoid, but the DMC has not Purges the Fluid lines.,",
        "A DPC fault prevented purge from occurring; See DPC for fault status",
        "-",
        "-",
        "-",
    ),
    (8193, 1): (
        "DMC 2-1",
        "DPC Acknowledge Error",
        "Check fiber optic cable and connections, Replace DMC Control PCB, Replace CCM",
        "Check DMC to DPC fiber optic cable and connections; Dirty or defective fiber optic; DPC power supply fuse or Control PCB;  DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8193, 2): (
        "DMC 2-2",
        "DPC Bus Off Error",
        "Check fiber optic cable and connections, Replace DMC Control PCB, Replace CCM",
        "Check DMC to DPC fiber optic cable and connections; Dirty or defective fiber optic; DPC power supply fuse or Control PCB;  DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8193, 3): (
        "DMC 2-3",
        "Reserved",
        "Check fiber optic cable and connections, Replace DMC Control PCB, Replace CCM",
        "No information available; Contact customer service",
        "-",
        "-",
        "-",
    ),
    (8194, 4): (
        "DMC 3-1",
        "CCM Acknowledge Error",
        "Check fiber optic cable and connections, Replace DMC Control PCB, Replace DPC Control PCB.,",
        "Check DMC to CCM fiber optic cable and connections; Dirty or defective fiber optic; Replace DMC Control PCB;  Replace CCM Control PCB",
        "-",
        "-",
        "-",
    ),
    (8194, 5): (
        "DMC 3-2",
        "CCM Bus Off Error",
        "Check fiber optic cable and connections, Replace DMC Control PCB, Replace DPC Control PCB.,",
        "Check DMC to CCM fiber optic cable and connections; Dirty or defective fiber-optic; Replace DMC Control PCB; Replace CCM Control PCB",
        "-",
        "-",
        "-",
    ),
    (8194, 6): (
        "DMC 3-3",
        "Reserved",
        "Check fiber optic cable and connections, Replace DMC Control PCB, Replace DPC Control PCB.,",
        "No information available; Contact customer service",
        "-",
        "-",
        "-",
    ),
    (8195, 1): (
        "DMC 4-1",
        "CCM Connection Loss",
        "Check fiber optic cable and connections, Replace DMC Control PCB, CCM",
        "Loss of communication with either DPC or DMC; check for dirty or defective fiber optic to either DPC or CCM;  See DPC and CCM status codes",
        "-",
        "-",
        "-",
    ),
    (8195, 2): (
        "DMC 4-2",
        "CCM Timeout",
        "-",
        "Loss of communication with either DPC or DMC; Check for dirty or defective fiber optic to either DPC or CCM;  See DPC and CCM status codes",
        "-",
        "-",
        "-",
    ),
    (8195, 3): (
        "DMC 4-3",
        "DPC Timeout",
        "-",
        "Loss of communication with DPC; Check for dirty or defective fiber-optic to DPC; See DPC status code.",
        "-",
        "-",
        "-",
    ),
    (8195, 4): (
        "DMC 4-4",
        "DPC error",
        "-",
        "Loss of communication with DPC; check for dirty or defective fiber-optic to  DPC; See DPC status code",
        "-",
        "-",
        "-",
    ),
    (8195, 5): (
        "DMC 4-5",
        "Reserved",
        "-",
        "No information available; Contact customer service",
        "-",
        "-",
        "-",
    ),
    (8195, 6): (
        "DMC 4-6",
        "Reserved",
        "-",
        "No information available; Contact customer service",
        "-",
        "-",
        "-",
    ),
    (8196, 1): (
        "DMC 5-1",
        "Short Sol 1 - H35 Plasma",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 2): (
        "DMC 5-2",
        "Short Sol 2 - Oxygen Plasma",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 3): (
        "DMC 5-3",
        "Short Sol 3 - Air Plasma",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 4): (
        "DMC 5-4",
        "Short Sol 4 - Nitrogen Plasma",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 5): (
        "DMC 5-5",
        "Short Sol 5 - Aux Plasma",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 6): (
        "DMC 5-6",
        "Short Sol 6 - Oxygen Shield",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 7): (
        "DMC 5-7",
        "Short Sol 7 - Air Shield",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 8): (
        "DMC 5-8",
        "Short Sol 8 - Nitrogen Shield",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 9): (
        "DMC 5-9",
        "Short Sol 9 - H2O Shield",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 10): (
        "DMC 5-10",
        "Short Sol 10 - Oxygen Preflow",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 11): (
        "DMC 5-11",
        "Short Sol 11 - Air Preflow",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 12): (
        "DMC 5-12",
        "Short Sol 12 - Nitrogen Preflow",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 13): (
        "DMC 5-13",
        "Short Sol 13 - Argon Marking",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 14): (
        "DMC 5-14",
        "Short Sol 14 - Air Marking",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
    (8196, 15): (
        "DMC 5-15",
        "Short Sol 15 - Nitrogen Marking",
        "Replace solenoid, Shorted wire harness, Defective DMC Control PCB",
        "Replace solenoid; Shorted wire harness; Defective DMC Control PCB",
        "-",
        "-",
        "-",
    ),
}
FDPC = {
    (12288, 1): (
        "DPC 1-1",
        "Plasma Disabled",
        "Enable plasma",
        "Enable Plasma;  Defective DPC Power Supply;  Defective DPC control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 2): (
        "DPC 1-2",
        "VDC 24 fault",
        "Check/replace DPC power supply & fuses, Replace DPC control PCB",
        "Check /replace DPC power supply output fuse (F2); Defective DPC power supply; Replace DPC control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 3): (
        "DPC 1-3",
        "VDC 12 fault",
        "replace DPC power supply, Replace DPC control PCB",
        "replace DPC power supply; Replace DPC control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 4): (
        "DPC 1-4",
        "VDC 12 fault",
        "replace DPC power supply, Replace DPC control PCB",
        "replace DPC power supply; Replace DPC control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 5): (
        "DPC 1-5",
        "VDC 5 fault",
        "replace DPC power supply,Replace DPC control PCB",
        "replace DPC power supply; Replace DPC control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 6): (
        "DPC 1-6",
        "Analog Reference fault",
        "Replace DPC Control PCB",
        "Replace DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 7): (
        "DPC 1-7",
        "ADC voltage fault",
        "Replace DPC Control PCB",
        "Replace DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12288, 8): ("DPC 1-8", "Reserved", "-", "Reserved 1-8", "-", "-", "-"),
    (12288, 9): (
        "DPC 1-9",
        "Valve not configured",
        "Resend process from TSC 3000 / CNC",
        "Select process and send to plasma system",
        "-",
        "-",
        "-",
    ),
    (12288, 10): (
        "DPC 1-10",
        "DPC is locked",
        "Process loading, wait until finished",
        "Process loading  wait until finished",
        "-",
        "-",
        "-",
    ),
    (12289, 1): (
        "DPC 2-1",
        "DMC Acknowledge error",
        "Fiber optic cable, DPC Control PCB",
        "Check and/or replace Fiber optic cable; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12289, 2): (
        "DPC 2-2",
        "Control Timeout",
        "Program firmware Fault, consult factory",
        "Program firmware fault  consult factory",
        "-",
        "-",
        "-",
    ),
    (12289, 3): (
        "DPC 2-3",
        "Control Protocol Error",
        "Program firmware Fault, consult factory",
        "Program firmware fault  consult factory",
        "-",
        "-",
        "-",
    ),
    (12289, 4): (
        "DPC 2-4",
        "Bus off",
        "Fiber optic cable, DPC Control PCB",
        "Check and/or replace Fiber optic cable; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12289, 5): (
        "DPC 2-5",
        "DMC Comm. Error",
        "Physical ,Fiber optic cable,DPC Control PCB",
        "Check and/or replace Fiber optic cable; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12290, 1): (
        "DPC 3-1",
        "Plasma Gas High (>145 PSI)",
        "Reduce pressure from gas supply, defective pressure sensor (PS4),",
        "Reduce pressure from Plasma gas supply; defective pressure sensor (PS4)",
        "-",
        "-",
        "-",
    ),
    (12290, 2): (
        "DPC 3-2",
        "Pilot Gas High (>145 PSI)",
        "Reduce pressure from gas supply, defective pressure sensor (PS3),",
        "Reduce pressure from Pilot gas supply; defective pressure sensor (PS3)",
        "-",
        "-",
        "-",
    ),
    (12290, 3): (
        "DPC 3-3",
        "Shield Gas High (>145 PSI)",
        "Reduce pressure from gas supply, defective pressure sensor (PS1),",
        "Reduce pressure from Shield gas supply; defective pressure sensor (PS1)",
        "-",
        "-",
        "-",
    ),
    (12290, 4): (
        "DPC 3-4",
        "Shield H2O High (>145 PSI)",
        "Reduce pressure from gas supply, defective pressure sensor (PS2),",
        "Reduce pressure from Water fluid supply; defective pressure sensor (PS2)",
        "-",
        "-",
        "-",
    ),
    (12291, 1): (
        "DPC 4-1",
        "Plasma High (V5) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 2): (
        "DPC 4-2",
        "Plasma Low (V4) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 3): (
        "DPC 4-3",
        "Pilot (V3) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 4): (
        "DPC 4-4",
        "Shield Gas (V1) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 5): (
        "DPC 4-5",
        "Shield H2O (V2) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 6): (
        "DPC 4-6",
        "Vent  (SOL2) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 7): (
        "DPC 4-7",
        "Cut (SOL3) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 8): (
        "DPC 4-8",
        "Mark (SOL1) shorted",
        "Check for shorted wire harness, Replace valve",
        "Check for shorted wire harness; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 9): (
        "DPC 4-9",
        "Vent (SOL2) open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 10): (
        "DPC 4-10",
        "Cut (SOL3) open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12291, 11): (
        "DPC 4-11",
        "Mark (SOL1) open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12292, 1): (
        "DPC 5-1",
        "Valve open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12292, 2): (
        "DPC 5-2",
        "DPC inlet Supply pressure low",
        "Raise plasma inlet pressure, check for DMC valve not open, restriction in gas supply/hoses",
        "Raise plasma inlet pressure; Check for DMC valve not open; Restriction in gas supply/hoses",
        "-",
        "-",
        "-",
    ),
    (12292, 3): (
        "DPC 5-3",
        "Outlet pressure too low",
        "Leak in plasma hose to torch, defective control valve (V5); defective pressure sensor (PS6); DPC Control PCB",
        "Leak in plasma hose to torch; Defective control valve (V5); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12292, 4): (
        "DPC 5-4",
        "Outlet pressure low",
        "Leak in plasma hose to torch, defective control valve (V5); defective pressure sensor (PS6); DPC Control PCB",
        "Leak in plasma hose to torch; Defective control valve (V5); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12292, 5): (
        "DPC 5-5",
        "Outlet pressure Too high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve (V5); defective pressure sensor (PS6); DPC Control PCB",
        "Restriction in plasma hose; torch or DPC manifold; Defective control valve (V5); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12292, 6): (
        "DPC 5-6",
        "Outlet pressure high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve (V5); defective pressure sensor (PS6); DPC Control PCB",
        "Restriction in plasma hose; torch or DPC manifold; Defective control valve (V5); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12293, 1): (
        "DPC 6-1",
        "Valve open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12293, 2): (
        "DPC 6-2",
        "DPC inlet Supply pressure low",
        "Raise plasma inlet pressure, check for DMC valve not open, restriction in gas supply/hoses",
        "Raise plasma inlet pressure; Check for DMC valve not open; Restriction in gas supply/hoses",
        "-",
        "-",
        "-",
    ),
    (12293, 3): (
        "DPC 6-3",
        "Outlet pressure  too low",
        "Leak in plasma hose to torch, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Leak in plasma hose to torch; Defective control valve (V4); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12293, 4): (
        "DPC 6-4",
        "Outlet pressure low",
        "Leak in plasma hose to torch, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Leak in plasma hose to torch; Defective control valve (V4); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12293, 5): (
        "DPC 6-5",
        "Outlet pressure too high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Restriction in plasma hose to torch; torch or DPC manifold; Defective control valve (V4); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12293, 6): (
        "DPC 6-6",
        "Outlet pressure high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Restriction in plasma hose; torch or DPC manifold; Defective control valve (V4); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12294, 1): (
        "DPC 7-1",
        "Valve open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12294, 2): (
        "DPC 7-2",
        "DPC inlet Supply pressure low",
        "Raise plasma inlet pressure, check for DMC valve not open, restriction in gas supply/hoses",
        "Raise pilot inlet pressure; Check for DMC valve not open; Restriction in gas supply/hoses",
        "-",
        "-",
        "-",
    ),
    (12294, 3): (
        "DPC 7-3",
        "Outlet pressure  too low",
        "Leak in plasma hose to torch, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Leak in plasma hose to torch; Defective control valve (V3); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12294, 4): (
        "DPC 7-4",
        "Outlet pressure low",
        "Leak in plasma hose to torch, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Leak in plasma hose to torch; Defective control valve (V3); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12294, 5): (
        "DPC 7-5",
        "Outlet pressure too high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Restriction in plasma hose to torch; torch or DPC manifold; Defective control valve (V3); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12294, 6): (
        "DPC 7-6",
        "Outlet pressure high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve, defective pressure sensor (PS6); DPC Control PCB",
        "Restriction in plasma hose to torch; torch or DPC manifold; Defective control valve (V3); Defective pressure sensor (PS6); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12295, 1): (
        "DPC 8-1",
        "Valve open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12295, 2): (
        "DPC 8-2",
        "DPC inlet Supply pressure low",
        "Raise plasma inlet pressure, check for DMC valve not open, restriction in gas supply/hoses",
        "Raise shield gas inlet pressure; Check for DMC valve not open; Restriction in gas supply/hoses",
        "-",
        "-",
        "-",
    ),
    (12295, 3): (
        "DPC 8-3",
        "Outlet pressure  too low",
        "Leak in plasma hose to torch, defective control valve, defective pressure sensor (PS5); DPC Control PCB",
        "Leak in shield hose to torch; Defective control valve (V1); Defective pressure sensor (PS5); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12295, 4): (
        "DPC 8-4",
        "Outlet pressure low",
        "Leak in plasma hose to torch, defective control valve, defective pressure sensor (PS5); DPC Control PCB",
        "Leak in shield hose to torch; Defective control valve (V1); Defective pressure sensor (PS5); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12295, 5): (
        "DPC 8-5",
        "Outlet pressure too high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve, defective pressure sensor (PS5); DPC Control PCB",
        "Restriction in shield hose to torch; torch or DPC manifold; Defective control valve (V1); Defective pressure sensor (PS5); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12295, 6): (
        "DPC 8-6",
        "Outlet pressure high",
        "Restriction in plasma hose, torch, DPC manifold, defective control valve, defective pressure sensor",
        "Restriction in shield hose to torch; torch or DPC manifold; Defective control valve (V1); Defective pressure sensor (PS5); DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12296, 1): (
        "DPC 9-1",
        "Valve open",
        "Check for open connection, Replace valve",
        "Check for open connection; Replace valve",
        "-",
        "-",
        "-",
    ),
    (12296, 2): (
        "DPC 9-2",
        "DPC inlet Supply pressure low",
        "Raise plasma inlet pressure,check for DMC valve not open, restriction in gas supply/hoses",
        "Raise shield water inlet pressure; Check for DMC valve not open; Restriction in gas supply/hoses",
        "-",
        "-",
        "-",
    ),
    (12296, 3): (
        "DPC 9-3",
        "Outlet flow too low",
        "Restriction in shield hose, torch, DPC manifold, defective control valve, defective flow sensor (FS-1)); DPC Control PCB",
        "Leak in shield hose to torch; Defective control valve (V2); Defective pressure sensor (PS5) or flow sensor (FS-1) if equipped; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12296, 4): (
        "DPC 9-4",
        "Outlet flow low",
        "Restriction in shield hose, torch, DPC manifold, defective control valve, defective flow sensor (FS-1)); DPC Control PCB",
        "Leak in shield hose to torch; Defective control valve (V2); Defective pressure sensor (PS5)  or flow sensor (FS-1) if equipped; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12296, 5): (
        "DPC 9-5",
        "Outlet flow too high",
        "Leak in shield hose to torch, defective control valve, DPC Control PCB",
        "Restriction in shield hose to torch; torch or DPC manifold; Defective control valve (V2); Defective pressure sensor (PS5) or flow sensor (FS-1) if equipped; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
    (12296, 6): (
        "DPC 9-6",
        "Outlet flow high",
        "Leak in shield hose to torch, defective control valve, DPC Control PCB",
        "Restriction in shield hose to torch; torch or DPC manifold; Defective control valve (V2); Defective pressure sensor (PS5) or flow sensor (FS-1) if equipped; DPC Control PCB",
        "-",
        "-",
        "-",
    ),
}
